# set language
language: python

# python version
python:
  - "3.6"


# install app dependencies
# install other non app specific dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls


# run the tests using nosetest with a coverage report
scripts:
  - nosetests --with-coverage --cover-package=app


# Let coveralls know the test coverage after the tests are done.
script:
  - coveralls
