# set language
language: python

# python version
python:
  - "3.6"


# install app dependencies
# install other non app specific dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls


# some setup
  - export FLASK_APP='run.py'
  - psql -c 'create database sendit;' -U postgres
  - export DATABASE_URL='postgresql://postgres@localhost:5432/sendit'
  - python run.py


# run the tests using pytest with a coverage report
script:
  - pytest --cov-report term-missing --cov=app/api


# Let coveralls know the test coverage after the tests are done.
after_success:
  - coveralls
