# set language
language: python

# python version
python:
  - "3.6"


# install app dependencies
# install other non app specific dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls


# run the tests using pytest with a coverage report
scripts:
  - pytest --cov-report --term-missing --cov=app


# Let coveralls know the test coverage after the tests are done.
script:
  - coveralls
